project:
  type: website
  output-dir: doc

website:
  title: "Junpei Suzuki PhD"
  # google-analytics: "G-14289305692"
  page-footer: "Copyright 2026, Junpei Suzuki"
  navbar:
    logo: "figs/portrait_ghibli_closeup.png"
    left:
      - href: index.qmd
        text: Home
      - href: cv/cv.qmd
        text: CV
      - href: research/research.qmd
        text: Research
      - href: teaching/teaching.qmd
        text: Teaching
      # - href: seminar/seminar.qmd
      #   text: Seminar
    right: 
    - icon: envelope
      href: mailto:jsuzuki@komazawa-u.ac.jp
    - icon: person-circle
      href: https://researchmap.jp/junpeisuzuki-ps
    - icon: mortarboard-fill
      href: https://www.researchgate.net/profile/Junpei-Suzuki-2
    - icon: github
      href: https://github.com/junpei-suzuki
  # sidebar: 
  # - id: seminar
  #   title: "Seminar"
  #   style: "docked"
  #   background: light
  #   contents:
  #    - text: 鈴木ゼミについて
  #      href: seminar/seminar.qmd
  #    - text: メンバー
  #      href: seminar/member.qmd
  #    - text: 担当教員について
  #      href: seminar/about_js.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



